verifying cluster access

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -50,6 +50,14 @@ jobs:
       - name: Update kubectl context 
         run: |
              aws eks update-kubeconfig --region eu-north-1 --name simplebank --kubeconfig ~/.kube/config
+      
+      - name: Check Kubeconfig
+        run: |
+             cat ~/.kube/config
+     
+      - name: Validate Cluster Access
+        run: |
+             kubectl cluster-info --kubeconfig ~/.kube/config || echo "Failed to access the cluster"
 
       - name: Deploy to EKS
         run: |
